# Generated by Django 4.0.2 on 2022-02-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerto',
            field=models.TextField(blank=True),
        ),
    ]
