# Generated by Django 4.0.2 on 2022-02-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_excerto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='fotos_dos_posts/%Y/%m'),
        ),
    ]
